In [1]:
import numpy as np

In [2]:
A_12 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(A_12)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
transpose_12 = np.transpose(A_12)
print(transpose_12)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [4]:
determinan_12 = np.linalg.det(A_12)
print(determinan_12)

6.66133814775094e-16


In [10]:
B_12 = ([[1,4,5],
         [2,1,3]])
C_12 =([[8,0],
        [1,6],
        [5,4]])
K_12 = np.dot(B_12, C_12)
print("Hasil perkalian matriks adalah : ")
print(K_12)

Hasil perkalian matriks adalah : 
[[37 44]
 [32 18]]


In [7]:
tinggi_12 = [170,172,160,180,167,165,145,160.162,161,176,154,187]
rata_12 = np.mean(tinggi_12)
print('Rata rata tinggi mahasiswa angkatan 2023 adalah', rata_12)

Rata rata tinggi mahasiswa angkatan 2023 adalah 166.43016666666668


In [11]:
matriks_identitas_12 = np.eye(8)
print(matriks_identitas_12 )

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
